# Generated by Django 2.2.4 on 2019-09-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='Новостройка',
            field=models.NullBooleanField(max_length='Старое здание', verbose_name=True),
        ),
    ]
