# Generated by Django 2.2.4 on 2019-09-06 07:58

from django.db import migrations


def fill_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for house in Flat.objects.all():
        if house.construction_year >= 2015:
            house.new_building = True
        else:
            house.new_building = False
        house.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for house in Flat.objects.all():
        house.new_building = None
        house.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20190906_0944'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field, move_backward)
    ]
