# Generated by Django 2.2.4 on 2019-09-07 09:06

from django.db import migrations
import phonenumbers


class Migration(migrations.Migration):

    def filling_owner_phone_pure(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for phone in Flat.objects.all():
            parse_phone_number = phonenumbers.parse(phone.owners_phonenumber, "RU")
            phone.owner_phone_pure = phonenumbers.format_number(parse_phone_number,
                                                                phonenumbers.PhoneNumberFormat.E164)
            phone.save()

    dependencies = [
        ('property', '0009_auto_20190907_1144'),
    ]

    operations = [
        migrations.RunPython(filling_owner_phone_pure)
    ]
