# Generated by Django 2.2.4 on 2019-09-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    def copy_owners_to_owner(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')
        for owner in Flat.objects.all():
            Owner.objects.get_or_create(owner=owner.owner,
                                        owners_phonenumber=owner.owners_phonenumber,
                                        owner_phone_pure=owner.owner_phone_pure
                                        )
    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(copy_owners_to_owner)
    ]
