# Generated by Django 2.2.4 on 2019-09-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    def connect_flats_to_owners(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')
        for owner in Owner.objects.all():
            print(owner)
            flats = Flat.objects.filter(owner=owner.owner)
            for flat in flats:
                print(flat)
                owner.owner_flats.add(*[flat])

    dependencies = [
        ('property', '0013_auto_20190908_1840'),
    ]

    operations = [
        migrations.RunPython(connect_flats_to_owners)
    ]
